version: "3"

networks:
  backend:

services:
  firebase:
    build: .
    container_name: firebase
    networks:
      - backend
    ports:
      - 9099:9099 # Auth
      - 4000:4000 # Emulator Suite UI
      - 5001:5001 # Cloud Functions
      - 8080:8080 # Cloud Firestore
      - 9000:9000 # Realtime Database
      - 5000:5000 # Hosting
      - 8085:8085 # Pubsub
    volumes:
      - ./:/opt/workspace:cached
    working_dir: /opt/workspace
    tty: true
