version: "3"

services:
  sample-function:
    image: lambci/lambda:nodejs12.x
    ports:
      - 9001:9001
    environment:
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
      DOCKER_LAMBDA_DEBUG: 1
      TZ: "Asia/Tokyo"
    volumes:
      - ./lambda/sample-function:/var/task:rw,delegated
    tty: true
    command: index.handler
